version: '3'

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - rabbitmq
      - redis
    env_file:
      - .env
    networks:
        - looking_for_talents

  postgres:
    image: postgres:latest
    container_name: looking_for_talents_postgres
    volumes:
      - /data/db
    environment:
      POSTGRES_DB: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
        - looking_for_talents

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    container_name: looking_for_talents_rabbitmq
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
        - looking_for_talents

  redis:
    image: redis:latest
    container_name: looking_for_talents_redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data
    networks:
        - looking_for_talents

networks:
  looking_for_talents:
    external: true
