default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db_development_postgres

test:
  <<: *default
  database: db_test_postgres

production:
  <<: *default
  database: db_production_postgres
