default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db_development_postgres

test:
  <<: *default
  database: db_test_postgres

production:
  <<: *default
  database: db_production_postgres

amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: sa-east-1
  bucket: <%= ENV['AWS_BUCKET'] %>
