default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST') { 'postgres' } %>
  user: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: looking_for_talents_development_postgres

test:
  <<: *default
  database: looking_for_talents_test_postgres

production:
  <<: *default
  database: looking_for_talents_production_postgres
