name: "Looking for Talents CI"
on:
  push:
    branches:
      - master
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo Docker Image Build'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          file: ./Dockerfile
          tags: |
            yosh1tsune/looking-for-talents:v${{ github.run_number }}
            yosh1tsune/looking-for-talents:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    steps:
      - run: 'echo Deploy to Kubernetes Cluster'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Kube config
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yml
          images: |
            yosh1tsune/looking-for-talents:v${{ github.run_number }}
